use std::path::PathBuf;

use anyhow::{Result, bail};

pub(crate) fn run_init(output: PathBuf, force: bool) -> Result<()> {
    if output.exists() && !force {
        bail!(
            "Config file {} already exists. Use --force to overwrite.",
            output.display()
        );
    }

    let config = generate_default_config();
    std::fs::write(&output, config)?;
    println!("Created config file: {}", output.display());

    Ok(())
}

fn generate_default_config() -> String {
    #[cfg(target_os = "android")]
    let (storage_path, db_path) = ("/sdcard/vein/cache", "/sdcard/vein/vein.db");

    #[cfg(not(target_os = "android"))]
    let (storage_path, db_path) = ("./cache", "./vein.db");

    format!(
        r#"# Vein Configuration
# Generated by `vein init`

[server]
host = "0.0.0.0"
port = 8346

[storage]
path = "{storage_path}"

[database]
path = "{db_path}"

[logging]
level = "info"

# Uncomment to enable upstream proxy (required for fetching new gems)
# [upstream]
# url = "https://rubygems.org"
# For chain mode (Android -> Desktop vein):
# url = "http://192.168.x.x:8346"
"#
    )
}
